version: '3.4'

services:
  web:
    image: socialnetwork-web
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  chat:
    image: socialnetwork-chat
    build:
      context: .
      dockerfile: Chat/Chat.Web/Dockerfile
